name: Rust

on: [push]

jobs:
  build-api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run:
      - cd api
      - cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
