name: CI

on: [push]

jobs:
  build-api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Build
      run: |
        cd api
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
